title: Luca Volini
description: Data Scientist | Kaggle Contributor | Tensorflow
theme: jekyll-theme-cayman
li_in: https://www.linkedin.com/in/luca-volini-401658106/?locale=en_US
li_in_bug: /assets/images/LI-In-Bug.png
li_in_bug_footer: /assets/images/LI-In-Bug-footer.png
tf_dev_cert: https://api.accredible.com/v1/frontend/credential_website_embed_image/certificate/84368694
tf_cert_net: https://developers.google.com/certification/directory/tensorflow